name: Deploy Pupilens Landing Page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload Pupilens to DreamHost (SSH)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Pupilens via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "./*"
          target: "/home/foozsed/kerootica.com.br/lp-pupilens"